### ISSUE TITLE
beta fixes after review

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro.app#91]
- [x] - add empty pie-charts if no tokens to display and empty graphs with tokens
- [x] - add default "You have no active validators" as position 1 in validators section if no active validators for selected acc
- [x]  not_asap  - Proposal title and text formatting (too look good)
- [x] - add 'Not voted' if no vote at proposal page
- [x] - passport page: remove  `confirmed` from passport when created
- [x] - replace "Voting power" to "Rewards" calculate value in selected currency on top
- [x] - add Personal to APR tab
- [x] - passport value to new font
- [x] - RPDE to 'Daily profit" and new font
- [x] - if only one account in passport - remove 'View all' button
- [x] - Add votes separation to prop page
- [x] - tooltip logo blinks(moves) twice when new page is open, do the same when hover over element with tooltip

**Comment by bro-n-bro-2** [comment]
- [x] - Change Proposals to Governance
 - ![image](https://github.com/bro-n-bro/bro.app/assets/89855562/c80a22a1-f03c-4aa0-bdfb-d57570628ae3)
- [x] Add proposal to name
- [x] - Assets and Network tabs update description (swap their places)

- [x] - ![image](https://github.com/bro-n-bro/bro.app/assets/89855562/baafb7d5-79e5-4f88-8cf5-134de3f40e4c)

- [x] - After adding a new address label gets passport account name instead of added account Keplr name
 ![image](https://github.com/bro-n-bro/bro.app/assets/89855562/8d8821bd-0235-4078-9307-8c6bfa699c0c)

- [x] - Save passport image and nickname on passport creation page in local storage (not ASAP)
- [x] - Have a possibility to change passport nickname (not ASAP)

**Comment by bro-n-bro-2** [comment]
- [x] View all -> show all. Click on it again -> default view with one address. Fix clicking on account in view all mode.
- [x] Validators info in view all mode (show all validators)
- [x] Account name in validator info (View all)
- [ ] Update Votes in governance page (visualization) -> Details Votes button to show number of votes and delegators_shares_option

**Comment by bro-n-bro-99** [comment]
- [x] please fix page scrolling (mozilla browser not ok, chrome is ok)

![Screenshot 2023-08-15 at 15.42.30.png](https://images.zenhubusercontent.com/6267d13522693484f58725fb/787add3d-12e4-45e7-920b-760b0af7dfd0)

**Comment by bro-n-bro-99** [comment]
- [x] please check calculations in Demo

![Screenshot 2023-08-15 at 15.55.11.png](https://images.zenhubusercontent.com/6267d13522693484f58725fb/f7d9ef0a-3b21-4220-8742-a4570e47ace0)

**Comment by bro-n-bro-99** [comment]
- [ ] replace "<" with ">"

![Screenshot 2023-08-15 at 16.44.04.png](https://images.zenhubusercontent.com/6267d13522693484f58725fb/20d1664c-ee54-48c2-b3b7-864799b1bf7b)

**Comment by bro-n-bro-99** [comment]
- [x] fix to "Sign and Broadcast"

![Screenshot 2023-08-15 at 16.48.06.png](https://images.zenhubusercontent.com/6267d13522693484f58725fb/73f36b11-b479-472c-90e4-59fc60cae796)

**Comment by bro-n-bro-99** [comment]
- [x] fix to "Processing..."

![Screenshot 2023-08-15 at 16.49.18.png](https://images.zenhubusercontent.com/6267d13522693484f58725fb/a70ab383-73a2-4880-ae3a-17d402ddc1c9)
